import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

// If loading a variable font, you don't need to specify the font weight
const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
});

export const metadata: Metadata = {
  title: "Takuya Oshima",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={notoSansJP.className}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/vus0aaz.css"></link>
      </head>
      <body>
        <div className="flex flex-col h-lvh relative break-words">
          <Header />
          <div className="relative container mx-auto mt-34 md:mt-42 px-custom md:px-4 lg:px-0">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
