import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import type { Metadata } from "next";
import { Noto_Sans_JP, Roboto } from "next/font/google";
import "@/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeWrapper from "@/components/ThemeWrapper";


const notoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-noto-sans-jp",
  display: "swap",
});

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Takuya Oshima",
  description: "Generated by create next app",
};


export default async function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
}) {
  if (!(routing.locales as readonly string[]).includes(locale)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html lang={locale} className={`${roboto.variable} ${notoSansJP.variable} dark custom-cursor`}>
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/vus0aaz.css"></link>
      </head>
      <body>
        <ThemeWrapper> {/* クライアントコンポーネントでラップ */}
          <NextIntlClientProvider messages={messages}>
            <div className="flex flex-col min-h-screen relative break-words">
              <Header />
              <div className="relative container mx-auto mt-34 md:mt-42 px-custom md:px-4 lg:px-0">{children}</div>
              <Footer />
            </div>
          </NextIntlClientProvider>
        </ThemeWrapper>
      </body>
    </html>
  );
}
